spring:
  application:
    name: WebStore

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WebStore?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

  jackson:
    default-property-inclusion: non_empty
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-exp-time: ${JWT_ACCESS_TOKEN_EXPTIME}
  refresh-token-exp-time: ${JWT_REFRESH_TOKEN_EXPTIME}